POST http://localhost:3000/suppliers
content-Type: application/json

{
  "rfc": "RFC987654321X",
  "name": "Supplier 2",
  "description": "Proveedor de servicios",
  "number_phone": "0987654321",
  "email": "supplier2@example.com",
  "address": "Avenida Siempre Viva 742"
}

###
GET http://localhost:3000/suppliers


###
GET http://localhost:3000/suppliers/RFC987654321X


###
PUT http://localhost:3000/suppliers/RFC987654321X
content-Type: application/json

{
  "name": "Supplier 2 Updated",
  "description": "Proveedor actualizado",
  "number_phone": "0987654322",
  "email": "supplier2_updated@example.com",
  "address": "Nueva Dirección 123"
}

###
DELETE http://localhost:3000/suppliers/RFC987654321X