# Obtener todos los usuarios
GET http://localhost:3000/users
Accept: application/json

###
## Obtener un usuario por ID
GET http://localhost:3000/users/1
Accept: application/json

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}

###
# Actualizar un usuario existente
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "first_name": "Jane",
  "last_name": "Doe",
  "email": "janedoe@example.com"
}

###
# Eliminar un usuario por ID
DELETE http://localhost:3000/users/1
